### ISSUE TITLE
Pre-trained Weights Link Not Working

### ISSUE THREAD

**Issue by prajwalsingh** [googleinterns/IBRNet#20]
Dear Authors,

Thank you for making the code publicly available. 

The Google Drive link provided for the pre-trained weights is not working. Kindly provide the working link for the same.

**Comment by ArXee** [comment]
I met the same question,would you like to kindly provide the working link?

**Comment by 475651582** [comment]
I also came with the same issue, anyone knows how to solve it? all the download links are invalid currently.

**Comment by prajwalsingh** [comment]
@ArXee @475651582 Drop an email to Qianqian Wang. She will help you. By that time, you can access it from here for the ease of research [[onedrive](https://iitgnacin-my.sharepoint.com/:f:/g/personal/19210048_iitgn_ac_in/EoNFWeoB0KZFkT3bnAmOUZ0BjJJpswYJEfIs9vffz1MbjQ?e=gFjJtP)]

**Comment by 475651582** [comment]
@prajwalsingh Thanks! That saves my day!!!
