### ISSUE TITLE
The results generated with the pretrained weights looks weired

### ISSUE THREAD

**Issue by fomalhautb** [googleinterns/IBRNet#6]
I have downloaded the evaluation dataset and the pre-trained weights, but the generated with the pre-trained weights look like this:
![image](https://user-images.githubusercontent.com/14837467/131126786-8cd1bdd3-897c-4499-8e93-461746d2a772.png)
and the score is also low:
![image](https://user-images.githubusercontent.com/14837467/131126906-e6275935-a829-4d92-bca6-8dd62a42a1b6.png)
The scores for other test sets are also low.

**Comment by kyanagida3407** [comment]
Hi, have you had this problem resolved? I am having the same problem and the rendering results are not working．
